/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tarehart_rlbot_physics_cpp_NativeBallPredictor */

#ifndef _Included_tarehart_rlbot_physics_cpp_NativeBallPredictor
#define _Included_tarehart_rlbot_physics_cpp_NativeBallPredictor
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     tarehart_rlbot_physics_cpp_NativeBallPredictor
	* Method:    predictPath
	* Signature: (Ltarehart/rlbot/math/BallSlice;F)[Ltarehart/rlbot/math/BallSlice;
	*/
	JNIEXPORT jbyteArray JNICALL Java_tarehart_rlbot_physics_cpp_NativeBallPredictor_predictPath
	(JNIEnv *, jobject, jbyteArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
