# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameTickPacket.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GameTickPacket.proto',
  package='RLAPI',
  syntax='proto2',
  serialized_pb=_b('\n\x14GameTickPacket.proto\x12\x05RLAPI\"+\n\x08Vector3D\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\"\xae\x01\n\x07\x43\x61rInfo\x12!\n\x08Location\x18\x01 \x02(\x0b\x32\x0f.RLAPI.Vector3D\x12!\n\x08Rotation\x18\x02 \x02(\x0b\x32\x0f.RLAPI.Vector3D\x12\x1f\n\x05Score\x18\x03 \x02(\x0b\x32\x10.RLAPI.ScoreInfo\x12\x12\n\nSuperSonic\x18\x05 \x02(\x08\x12\x0b\n\x03\x42ot\x18\x06 \x02(\x08\x12\x0c\n\x04Team\x18\x07 \x02(\t\x12\r\n\x05\x42oost\x18\x04 \x02(\x05\"\xc4\x01\n\x08\x42\x61llInfo\x12!\n\x08Location\x18\x01 \x02(\x0b\x32\x0f.RLAPI.Vector3D\x12!\n\x08Rotation\x18\x02 \x02(\x0b\x32\x0f.RLAPI.Vector3D\x12!\n\x08Velocity\x18\x03 \x02(\x0b\x32\x0f.RLAPI.Vector3D\x12(\n\x0f\x41ngularVelocity\x18\x04 \x02(\x0b\x32\x0f.RLAPI.Vector3D\x12%\n\x0c\x41\x63\x63\x65leration\x18\x05 \x02(\x0b\x32\x0f.RLAPI.Vector3D\"M\n\tBoostInfo\x12!\n\x08Location\x18\x01 \x02(\x0b\x32\x0f.RLAPI.Vector3D\x12\x0e\n\x06\x41\x63tive\x18\x02 \x02(\x08\x12\r\n\x05Timer\x18\x03 \x02(\x05\"m\n\tScoreInfo\x12\r\n\x05Score\x18\x01 \x02(\x05\x12\r\n\x05Goals\x18\x02 \x02(\x05\x12\x0f\n\x07\x41ssists\x18\x03 \x02(\x05\x12\r\n\x05Saves\x18\x04 \x02(\x05\x12\r\n\x05Shots\x18\x05 \x02(\x05\x12\x13\n\x0b\x44\x65molitions\x18\x06 \x02(\x05\"{\n\x0eGameTickPacket\x12 \n\x08gamecars\x18\x01 \x03(\x0b\x32\x0e.RLAPI.CarInfo\x12$\n\ngameboosts\x18\x02 \x03(\x0b\x32\x10.RLAPI.BoostInfo\x12!\n\x08gameball\x18\x03 \x02(\x0b\x32\x0f.RLAPI.BallInfo')
)




_VECTOR3D = _descriptor.Descriptor(
  name='Vector3D',
  full_name='RLAPI.Vector3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='RLAPI.Vector3D.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='RLAPI.Vector3D.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='RLAPI.Vector3D.z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=74,
)


_CARINFO = _descriptor.Descriptor(
  name='CarInfo',
  full_name='RLAPI.CarInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Location', full_name='RLAPI.CarInfo.Location', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Rotation', full_name='RLAPI.CarInfo.Rotation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Score', full_name='RLAPI.CarInfo.Score', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SuperSonic', full_name='RLAPI.CarInfo.SuperSonic', index=3,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Bot', full_name='RLAPI.CarInfo.Bot', index=4,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Team', full_name='RLAPI.CarInfo.Team', index=5,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Boost', full_name='RLAPI.CarInfo.Boost', index=6,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=251,
)


_BALLINFO = _descriptor.Descriptor(
  name='BallInfo',
  full_name='RLAPI.BallInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Location', full_name='RLAPI.BallInfo.Location', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Rotation', full_name='RLAPI.BallInfo.Rotation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Velocity', full_name='RLAPI.BallInfo.Velocity', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AngularVelocity', full_name='RLAPI.BallInfo.AngularVelocity', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Acceleration', full_name='RLAPI.BallInfo.Acceleration', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=450,
)


_BOOSTINFO = _descriptor.Descriptor(
  name='BoostInfo',
  full_name='RLAPI.BoostInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Location', full_name='RLAPI.BoostInfo.Location', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Active', full_name='RLAPI.BoostInfo.Active', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Timer', full_name='RLAPI.BoostInfo.Timer', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=529,
)


_SCOREINFO = _descriptor.Descriptor(
  name='ScoreInfo',
  full_name='RLAPI.ScoreInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Score', full_name='RLAPI.ScoreInfo.Score', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Goals', full_name='RLAPI.ScoreInfo.Goals', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Assists', full_name='RLAPI.ScoreInfo.Assists', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Saves', full_name='RLAPI.ScoreInfo.Saves', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Shots', full_name='RLAPI.ScoreInfo.Shots', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Demolitions', full_name='RLAPI.ScoreInfo.Demolitions', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=531,
  serialized_end=640,
)


_GAMETICKPACKET = _descriptor.Descriptor(
  name='GameTickPacket',
  full_name='RLAPI.GameTickPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gamecars', full_name='RLAPI.GameTickPacket.gamecars', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gameboosts', full_name='RLAPI.GameTickPacket.gameboosts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gameball', full_name='RLAPI.GameTickPacket.gameball', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=642,
  serialized_end=765,
)

_CARINFO.fields_by_name['Location'].message_type = _VECTOR3D
_CARINFO.fields_by_name['Rotation'].message_type = _VECTOR3D
_CARINFO.fields_by_name['Score'].message_type = _SCOREINFO
_BALLINFO.fields_by_name['Location'].message_type = _VECTOR3D
_BALLINFO.fields_by_name['Rotation'].message_type = _VECTOR3D
_BALLINFO.fields_by_name['Velocity'].message_type = _VECTOR3D
_BALLINFO.fields_by_name['AngularVelocity'].message_type = _VECTOR3D
_BALLINFO.fields_by_name['Acceleration'].message_type = _VECTOR3D
_BOOSTINFO.fields_by_name['Location'].message_type = _VECTOR3D
_GAMETICKPACKET.fields_by_name['gamecars'].message_type = _CARINFO
_GAMETICKPACKET.fields_by_name['gameboosts'].message_type = _BOOSTINFO
_GAMETICKPACKET.fields_by_name['gameball'].message_type = _BALLINFO
DESCRIPTOR.message_types_by_name['Vector3D'] = _VECTOR3D
DESCRIPTOR.message_types_by_name['CarInfo'] = _CARINFO
DESCRIPTOR.message_types_by_name['BallInfo'] = _BALLINFO
DESCRIPTOR.message_types_by_name['BoostInfo'] = _BOOSTINFO
DESCRIPTOR.message_types_by_name['ScoreInfo'] = _SCOREINFO
DESCRIPTOR.message_types_by_name['GameTickPacket'] = _GAMETICKPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector3D = _reflection.GeneratedProtocolMessageType('Vector3D', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3D,
  __module__ = 'GameTickPacket_pb2'
  # @@protoc_insertion_point(class_scope:RLAPI.Vector3D)
  ))
_sym_db.RegisterMessage(Vector3D)

CarInfo = _reflection.GeneratedProtocolMessageType('CarInfo', (_message.Message,), dict(
  DESCRIPTOR = _CARINFO,
  __module__ = 'GameTickPacket_pb2'
  # @@protoc_insertion_point(class_scope:RLAPI.CarInfo)
  ))
_sym_db.RegisterMessage(CarInfo)

BallInfo = _reflection.GeneratedProtocolMessageType('BallInfo', (_message.Message,), dict(
  DESCRIPTOR = _BALLINFO,
  __module__ = 'GameTickPacket_pb2'
  # @@protoc_insertion_point(class_scope:RLAPI.BallInfo)
  ))
_sym_db.RegisterMessage(BallInfo)

BoostInfo = _reflection.GeneratedProtocolMessageType('BoostInfo', (_message.Message,), dict(
  DESCRIPTOR = _BOOSTINFO,
  __module__ = 'GameTickPacket_pb2'
  # @@protoc_insertion_point(class_scope:RLAPI.BoostInfo)
  ))
_sym_db.RegisterMessage(BoostInfo)

ScoreInfo = _reflection.GeneratedProtocolMessageType('ScoreInfo', (_message.Message,), dict(
  DESCRIPTOR = _SCOREINFO,
  __module__ = 'GameTickPacket_pb2'
  # @@protoc_insertion_point(class_scope:RLAPI.ScoreInfo)
  ))
_sym_db.RegisterMessage(ScoreInfo)

GameTickPacket = _reflection.GeneratedProtocolMessageType('GameTickPacket', (_message.Message,), dict(
  DESCRIPTOR = _GAMETICKPACKET,
  __module__ = 'GameTickPacket_pb2'
  # @@protoc_insertion_point(class_scope:RLAPI.GameTickPacket)
  ))
_sym_db.RegisterMessage(GameTickPacket)


# @@protoc_insertion_point(module_scope)
